# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPVcet_YQp1SyS4e5nG9f5nxs-8I6oSJ
"""

n = 0
while n < 5: 
    x = input("Please enter a value: ")
    k = x.find('.')
    if k >= 0:
      x = float(x) 
    elif x.isnumeric():
      x = int(x)

    print(f'The type of your value is:{type(x)}')
    print("And your value is:{}".format(x))
    n = n+1

print("You have finished entering your 5 values")