# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfBsWnEQXI-S2ZybEj_Wsikhk4yne5Er
"""

name = input("Please enter your name: ")
surname = input("Please enter your surname: ")
age = input("Please enter your age: ")
birthdate = input("Please enter the year you were born: ")

myList = []
myList.append(name)
myList.append(surname)
myList.append(age)
myList.append(birthdate)

info = ["name", "surname", "age", "birthdate"]

#displaying the list
k = 0
for i in myList:       
  if k < len(info):
    print('Your {} is: '.format(info[k]) + format(i))
  k = k+1

#age check
age = int(age)   #typecasting
if age < 18:
  print("You can't go out because it's too dangerous")
else:
  print("You can go out to the street")