# -*- coding: utf-8 -*-
"""Hw3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXVc04p6hrFaEgTL79NhlgOTL_CM2QhG
"""

import random

#assuming that we hang the man after 10 incorrect guesses

name = input("Please enter your name: ")
print("Welcome", name)

#finding a random word
def chooseWord():
  words = ["able", "about", "acid", "across", "among", "attention", "beautiful","account","bucket","condition","down","experience","business","change","fiction","transport","distribution","bridge","committee","discovery"]
  i = random.randint(0, len(words) - 1)
  return words[i]

#searching the word
def searchWord(word, letter, score):
  guess = False
  for i in word:
    if letter == word.index(i):
      print("You found a match!")
      guess = True

  if guess == False:
    print("You could not find a match! You will get a penalty.")

  return guess

score = 10

myWord = chooseWord()
guess = input("Please guess a letter: ")

while (score >= 1):
  if not searchWord(myWord, guess, score):
    score = score-1
    print("You have", score, " chances left")
  guess = input("Please guess a letter: ")

if score != 0:
  print("You won the game")
else:
  print("You lost the game")

print("The word was:", myWord)